In [7]:
!pip install pyprep

Traceback (most recent call last):
  File "/Users/admin/opt/anaconda3/envs/deepfake/bin/pip", line 5, in <module>
    from pip import main
  File "/Users/admin/opt/anaconda3/envs/deepfake/lib/python3.11/site-packages/pip/__init__.py", line 21, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "/Users/admin/opt/anaconda3/envs/deepfake/lib/python3.11/site-packages/pip/_vendor/requests/__init__.py", line 65, in <module>
    from . import utils
  File "/Users/admin/opt/anaconda3/envs/deepfake/lib/python3.11/site-packages/pip/_vendor/requests/utils.py", line 27, in <module>
    from .cookies import RequestsCookieJar, cookiejar_from_dict
  File "/Users/admin/opt/anaconda3/envs/deepfake/lib/python3.11/site-packages/pip/_vendor/requests/cookies.py", line 172, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: modu

In [9]:
#installing the libraries
import mne
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import PyQt5
from pathlib import Path

#the following magic line will make all of your figures to be of the chosen size (in inches)
%matplotlib qt5

In [25]:
raw = mne.io.read_raw("sub-026_experiment.fif", preload=True)
raw.plot()

Opening raw data file sub-026_experiment.fif...


/var/folders/0d/srp3ljxn63z_0h2m39s7f7sw0000gp/T/ipykernel_52188/1351300070.py:1: RuntimeWarning: This filename (sub-026_experiment.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  raw = mne.io.read_raw("sub-026_experiment.fif", preload=True)


Isotrak not found
    Range : 0 ... 2465474 =      0.000 ...  4930.948 secs
Ready.
Reading 0 ... 2465474  =      0.000 ...  4930.948 secs...
Using pyopengl with version 3.1.6


Channels marked as bad:
none


In [ ]:
ica = mne.preprocessing.ICA(n_components = 20)
ica.fit(raw)

Fitting ICA to data using 60 channels (please be patient, this may take a while)


/var/folders/0d/srp3ljxn63z_0h2m39s7f7sw0000gp/T/ipykernel_52188/3724474555.py:2: RuntimeWarning: The data has not been high-pass filtered. For good ICA performance, it should be high-pass filtered (e.g., with a 1.0 Hz lower bound) before fitting ICA.
  ica.fit(raw)


Selecting by number: 20 components


In [ ]:
ica.plot_sources(raw)

In [10]:
sbj_id = 'sub-026'
file_path = str(f'{sbj_id}.vhdr')
raw = mne.io.read_raw_brainvision(file_path, eog=['HEOG', 'VEOG'], misc=['BIP1'], preload=True)
raw.plot(block = True)
raw.crop_by_annotations(raw.annotations[raw.annotations.description == 'select'])
event_list = mne.events_from_annotations(raw)[0]
len(event_list[event_list[:, 2] == 32])

Extracting parameters from sub-026.vhdr...
Setting channel info structure...
Reading 0 ... 2465474  =      0.000 ...  4930.948 secs...
Using qt as 2D backend.
Using pyopengl with version 3.1.6
Channels marked as bad:
['T7']
Used Annotations descriptions: ['New Segment/', 'Stimulus/S  1', 'Stimulus/S  2', 'Stimulus/S  3', 'Stimulus/S  4', 'Stimulus/S  5', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 20', 'Stimulus/S 21', 'Stimulus/S 22', 'Stimulus/S 32']


122

In [12]:
sbj_id = 'sub-026'
file_path = str(f'{sbj_id}.vhdr')
raw = mne.io.read_raw_brainvision(file_path, eog=['HEOG', 'VEOG'], misc=['BIP1'], preload=True)

Extracting parameters from sub-026.vhdr...
Setting channel info structure...
Reading 0 ... 2465474  =      0.000 ...  4930.948 secs...


In [13]:
event_list = mne.events_from_annotations(raw)[0]
len(event_list[event_list[:, 2] == 3])

Used Annotations descriptions: ['New Segment/', 'Stimulus/S  1', 'Stimulus/S  2', 'Stimulus/S  3', 'Stimulus/S  4', 'Stimulus/S  5', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 20', 'Stimulus/S 21', 'Stimulus/S 22', 'Stimulus/S 32']


572

In [24]:
raw.save('sub-026_experiment.fif', overwrite = True)

Writing /Users/admin/Downloads/sub-026_experiment.fif


/var/folders/0d/srp3ljxn63z_0h2m39s7f7sw0000gp/T/ipykernel_52188/668729922.py:1: RuntimeWarning: This filename (/Users/admin/Downloads/sub-026_experiment.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  raw.save('sub-026_experiment.fif', overwrite = True)


Closing /Users/admin/Downloads/sub-026_experiment.fif
[done]


In [15]:
event_list

array([[      0,       0,   99999],
       [  28211,       0,       1],
       [  28711,       0,      12],
       ...,
       [2456923,       0,       3],
       [2457231,       0,       4],
       [2457406,       0,       5]])

In [16]:
raw.crop_by_annotations(raw.annotations[raw.annotations.description == 'select'])
event_list = mne.events_from_annotations(raw)[0]
len(event_list[event_list[:, 2] == 32])

Used Annotations descriptions: ['New Segment/', 'Stimulus/S  1', 'Stimulus/S  2', 'Stimulus/S  3', 'Stimulus/S  4', 'Stimulus/S  5', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 20', 'Stimulus/S 21', 'Stimulus/S 22', 'Stimulus/S 32']


122

In [17]:
#raw.crop(tmax = 3022)
event_list = mne.events_from_annotations(raw)[0]
len(event_list[event_list[:, 2] == 3])

Used Annotations descriptions: ['New Segment/', 'Stimulus/S  1', 'Stimulus/S  2', 'Stimulus/S  3', 'Stimulus/S  4', 'Stimulus/S  5', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 20', 'Stimulus/S 21', 'Stimulus/S 22', 'Stimulus/S 32']


572

In [18]:
event_list

array([[      0,       0,   99999],
       [  28211,       0,       1],
       [  28711,       0,      12],
       ...,
       [2456923,       0,       3],
       [2457231,       0,       4],
       [2457406,       0,       5]])

In [19]:
def find_bads(raw):
    nc = pyprep.find_noisy_channels.NoisyChannels(raw.copy().pick_types(eeg=True))
    nc.find_bads_by_deviation(2.5)
    return nc.get_bads()

In [20]:
rename_mapping = {
    "FCz": "C1",
    "C1": "C5",
    "C5": "TP7",
    "TP7": "CP3",
    "CP3": "P1",
    "P1": "P5",
    "P5": "PO7",
    "PO7": "PO3",
    "PO3": "POz",
    "POz": "PO4",
    "PO4": "PO8",
    "PO8": "P6",
    "P6": "P2",
    "P2": "CPz",
    "CPz": "CP4",
    "CP4": "TP8",
    "TP8": "C6",
    "C6": "C2",
    "C2": "FC4",
    "FC4": "FT8",
    "FT8": "F6",
    "F6": "AF8",
    "F2": "AF4",
    "AF4": "F2",
    "AF8": "FCz"
}
montage = mne.channels.make_standard_montage("standard_1020")

In [21]:
def data_cropper(raw):
    event_list = mne.events_from_annotations(raw)[0]
    t1 = (event_list[event_list[:, 2] == 32][61, 0] + 500)/500
    t2 = (event_list[event_list[:, 2] == 1][3*62, 0] - 500)/500
    try:
        t3 = (event_list[event_list[:, 2] == 32][121, 0] + 500)/500
    except:
        t3 = (event_list[event_list[:, 2] == 32][120, 0] + 500)/500
    raw1 = raw.copy().crop((event_list[1,0] - 1000)/500, t1)
    raw2 = raw.copy().crop(t2, t3)
    output = [raw1, raw2]
    t1 = ((event_list[event_list[:, 2] == 2][0, 0])-500)/500
    t4 = ((event_list[event_list[:, 2] == 5][449, 0])+500)/500
    output.append(raw.copy().crop(t1, t4))
    #output[0].plot()
    #output[1].plot()
    #output[2].plot()
    return output

Можно сразу запустить блок ниже

In [22]:
for i in [11, 12, 13, 14, 15, 16, 17, 18, 19, 22, 23, 24, 25, 5]:
    if len(str(i)) < 2:
        sbj_id = 'sub-00' + str(i)
    else:
        sbj_id = 'sub-0' + str(i)
    print('Start working with:', sbj_id)
    file_path = str(f'{sbj_id}.vhdr')
    raw = mne.io.read_raw_brainvision(file_path, eog=['HEOG', 'VEOG'], misc=['BIP1'], preload=True)
    raw.rename_channels(rename_mapping)
    raw.set_montage(montage)
    raws = data_cropper(raw)
    output = []
    for i in range(3):
        raw = raws[i]
        raw.notch_filter(50) 
        raw.filter(1,45)
        #raw.info['bads'] = find_bads(raw)
        #print('Delete channels №:', raw.info['bads'])
        raw.plot(block = True)
        raw.interpolate_bads()
        ica = mne.preprocessing.ICA(n_components=20)
        ica.fit(raw)
        #ica.plot_sources(raw)
        #ica.plot_components()
        #raw.plot(block = True)
        bad_answers = []
        bad_ans, corrs = ica.find_bads_eog(raw, measure = 'correlation', threshold = 0.4)
        bad_answers += bad_ans
        #manually_bad = input()
        #bad_answers += list(map(int, manually_bad.split()))
        ica.exclude = bad_ans
        print('Delete components №:', ica.exclude)
        ica.apply(raw)
        output.append(raw.copy())
    raw = mne.concatenate_raws(output[0:2])
    raw.save(f'{sbj_id}_experiment.fif', overwrite = True)
    output[2].save(f'{sbj_id}_control.fif', overwrite = True)
    del output, raws, raw

Start working with: sub-011
Extracting parameters from sub-011.vhdr...


FileNotFoundError: [Errno 2] No such file or directory: '/Users/admin/Downloads/sub-011.vhdr'

In [4]:
sbj_id = 'sub-001'
file_path = str(f'{sbj_id}.vhdr')
raw = mne.io.read_raw_brainvision(file_path, eog=['HEOG', 'VEOG'], misc=['BIP1'], preload=True)
raw.plot()

Extracting parameters from sub-001.vhdr...
Setting channel info structure...
Reading 0 ... 2072849  =      0.000 ...  4145.698 secs...


2025-03-05 17:43:52,648 - OpenGL.acceleratesupport - INFO - No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'


Using qt as 2D backend.


Channels marked as bad:
none
Attempting to create new mne-python configuration file:
C:\Users\Семён\.mne\mne-python.json


In [ ]:
for i in range(1, 16):
    if len(str(i)) < 2:
        sbj_id = 'sub-00' + str(i)
    else:
        sbj_id = 'sub-0' + str(i)
    file_path = f'{sbj_id}_preprocessing.fif'
    raw = mne.io.read_raw_fif(file_path, preload = True)
    raw.plot(block = True)
    raw.interpolate_bads()
    raw.save(f'{sbj_id}_preprocessing.fif', overwrite = True)

In [40]:
sbj_id = 'sub-001'
file_path = f'{sbj_id}_experiment.fif'
raw = mne.io.read_raw_fif(file_path)
raw.plot(block = True)
raw.interpolate_bads()
events = mne.events_from_annotations(raw, event_id = lambda x: int(x.split()[1]))[0]

Opening raw data file sub-008_experiment.fif...
    Range : 33264 ... 1333124 =     66.528 ...  2666.248 secs
Ready.


C:\Users\Семён\AppData\Local\Temp\ipykernel_24892\2191249748.py:3: RuntimeWarning: This filename (sub-008_experiment.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  raw = mne.io.read_raw_fif(file_path)


Channels marked as bad:
none
Used Annotations descriptions: ['Stimulus/S  1', 'Stimulus/S  3', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 20', 'Stimulus/S 21', 'Stimulus/S 22', 'Stimulus/S 32']
121
{32, 1, 3, 11, 12, 20, 21, 22}


In [26]:
events

(array([[  34264,       0,       1],
        [  34764,       0,       4],
        [  35531,       0,       3],
        ...,
        [1331191,       0,       7],
        [1331941,       0,       6],
        [1332624,       0,       8]]),
 {'Stimulus/S  1': 1,
  'Stimulus/S  3': 2,
  'Stimulus/S 11': 3,
  'Stimulus/S 12': 4,
  'Stimulus/S 20': 5,
  'Stimulus/S 21': 6,
  'Stimulus/S 22': 7,
  'Stimulus/S 32': 8})

___________________

In [47]:
events = mne.events_from_annotations(raw)[0]
len(events[events[:, 2]==5])

Used Annotations descriptions: ['New Segment/', 'Stimulus/S  1', 'Stimulus/S  2', 'Stimulus/S  3', 'Stimulus/S  4', 'Stimulus/S  5', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 20', 'Stimulus/S 21', 'Stimulus/S 22', 'Stimulus/S 32']


102

Channels marked as bad:
none
Channels marked as bad:
none
Channels marked as bad:
none


In [46]:
montage = mne.channels.make_standard_montage("standard_1020")

In [47]:
rename_mapping = {
    "FCz": "C1",
    "C1": "C5",
    "C5": "TP7",
    "TP7": "CP3",
    "CP3": "P1",
    "P1": "P5",
    "P5": "PO7",
    "PO7": "PO3",
    "PO3": "POz",
    "POz": "PO4",
    "PO4": "PO8",
    "PO8": "P6",
    "P6": "P2",
    "P2": "CPz",
    "CPz": "CP4",
    "CP4": "TP8",
    "TP8": "C6",
    "C6": "C2",
    "C2": "FC4",
    "FC4": "FT8",
    "FT8": "F6",
    "F6": "AF8",
    "F2": "AF4",
    "AF4": "F2",
    "AF8": "FCz"
}
montage = mne.channels.make_standard_montage("standard_1020")

In [48]:
raw.rename_channels(rename_mapping)

<RawBrainVision | sub-016.eeg, 62 x 2159900 (4319.8 s), ~1021.7 MB, data loaded>

In [52]:
sbj_id = 'sub-031'
file_path = str(f'{sbj_id}.vhdr')
raw = mne.io.read_raw_brainvision(file_path, eog=['HEOG', 'VEOG'], misc=['BIP1'], preload=True)
raw.plot()

Extracting parameters from sub-031.vhdr...
Setting channel info structure...
Reading 0 ... 2128574  =      0.000 ...  4257.148 secs...


Channels marked as bad:
none
